### ISSUE TITLE
Why Zxing Maui barcode scanner crashes on IOS?

### ISSUE THREAD

**Issue by ThomasCarltonInPerson** [Redth/ZXing.Net.Maui#137]
Hi,

I'm using Zxing barcode scanner on an empty project as follows :

XAML : 
	<?xml version="1.0" encoding="utf-8" ?>
	<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
				 xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
				 x:Class="CameraTest.MainPage"
				 xmlns:zxing="clr-namespace:ZXing.Net.Maui.Controls;assembly=ZXing.Net.MAUI">

		<ScrollView>
			<VerticalStackLayout
				Spacing="25"
				Padding="30,0"
				VerticalOptions="Center">

				<zxing:CameraBarcodeReaderView x:Name="cameraBarcodeReaderView" />
			</VerticalStackLayout>
		</ScrollView>

	</ContentPage>

C#

	using ZXing.Net.Maui;

	namespace CameraTest;

	public partial class MainPage : ContentPage
	{
		int count = 0;

		public MainPage()
		{
			InitializeComponent();

			cameraBarcodeReaderView.Options = new BarcodeReaderOptions
			{
				Formats = BarcodeFormats.OneDimensional,
				AutoRotate = true,
				Multiple = true
			};
		}
	}

MauiProgram.cs

	using ZXing.Net.Maui;
	using Microsoft.Extensions.Logging;

	namespace CameraTest;

	public static class MauiProgram
	{
		public static MauiApp CreateMauiApp()
		{
			var builder = MauiApp.CreateBuilder();
			builder
				.UseMauiApp<App>()
				.UseBarcodeReader()
				.ConfigureFonts(fonts =>
				{
					fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
					fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
				});

	#if DEBUG
			builder.Logging.AddDebug();
	#endif

			return builder.Build();
		}
	}

Info.plist : 

	<key>NSCameraUsageDescription</key>
	<string>This app uses barcode scanning to...</string>

But when running the app on IPhone 14 iOS 16.4 simulator, I'm getting the following error. By the way, I didn't write a single line of my own code.

Does anyway know whats wrong with the Zxing barcode please ?

Thanks. 

[![enter image description here][1]][1]

	{System.ArgumentNullException: Value cannot be null. (Parameter 'device')
	   at ObjCRuntime.ThrowHelper.ThrowArgumentNullException(String argumentName)
	   at ObjCRuntime.NativeObjectExtensions.GetNonNullHandle(INativeObject self, String argumentName)
	   at AVFoundation.AVCaptureDeviceInput..ctor(AVCaptureDevice device, NSError& error)
	   at ZXing.Net.Maui.CameraManager.UpdateCamera()
	   at ZXing.Net.Maui.CameraManager.UpdateCameraLocation(CameraLocation cameraLocation)
	   at ZXing.Net.Maui.CameraBarcodeReaderViewHandler.<>c.<.cctor>b__24_1(CameraBarcodeReaderViewHandler handler, ICameraBarcodeReaderView virtualView)
	   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[ZXing.Net.Maui.ICameraBarcodeReaderView, ZXing.Net.Maui, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null],[ZXing.Net.Maui.CameraBarcodeReaderViewHandler, ZXing.Net.Maui, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
	   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
	   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
	   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
	   at Microsoft.Maui.Handlers.ViewHandler`2[[ZXing.Net.Maui.ICameraBarcodeReaderView, ZXing.Net.Maui, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null],[UIKit.UIView, Microsoft.iOS, Version=16.4.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].SetVirtualView(IView view)
	   at Microsoft.Maui.Handlers.ViewHandler`2[[ZXing.Net.Maui.ICameraBarcodeReaderView, ZXing.Net.Maui, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null],[UIKit.UIView, Microsoft.iOS, Version=16.4.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].SetVirtualView(IElement view)
	   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
	   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
	   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
	   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
	   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
	   at Microsoft.Maui.Handlers.LayoutHandler.SetVirtualView(IView view)
	   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.LayoutView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
	   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
	   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
	   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
	   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
	   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
	   at Microsoft.Maui.Handlers.ScrollViewHandler.UpdateContentView(IScrollView scrollView, IScrollViewHandler handler)
	   at Microsoft.Maui.Handlers.ScrollViewHandler.MapContent(IScrollViewHandler handler, IScrollView scrollView)
	   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IScrollView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IScrollViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
	   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
	   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
	   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
	   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IScrollView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[UIKit.UIScrollView, Microsoft.iOS, Version=16.4.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].SetVirtualView(IView view)
	   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IScrollView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[UIKit.UIScrollView, Microsoft.iOS, Version=16.4.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].SetVirtualView(IElement view)
	   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
	   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
	   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
	   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
	   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
	   at Microsoft.Maui.Handlers.ContentViewHandler.UpdateContent(IContentViewHandler handler)
	   at Microsoft.Maui.Handlers.ContentViewHandler.MapContent(IContentViewHandler handler, IContentView page)
	   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IContentViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
	   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
	   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
	   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
	   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view)
	   at Microsoft.Maui.Handlers.ContentViewHandler.SetVirtualView(IView view)
	   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
	   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
	   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
	   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
	   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
	   at Microsoft.Maui.Platform.ViewExtensions.ToHandler(IView view, IMauiContext context)
	   at Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRootRenderer.SetPageRenderer(Page page, ShellContent shellContent)
	   at Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRootRenderer.LoadRenderers()
	   at Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRootRenderer.ViewDidLoad()
	   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
	   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
	   at CameraTest.Program.Main(String[] args) in D:\Maui\annex_apps\CameraTest\CameraTest\Platforms\iOS\Program.cs:line 13}

  [1]: https://i.stack.imgur.com/jav0b.png

**Comment by tigreye007** [comment]
We are having the exact same issue.  Latest prerelease version (0.3.0-preview.1)

Visual Studio Community v17.7.4
Xcode v14.3

**Comment by madmapper** [comment]
This is because you are using the simulator, which has no camera.  You need to check device type before you flip on the bar code reader view.
