### ISSUE TITLE
Laser Scan is not working after triggering Zxing CameraBarcodeReaderView.

### ISSUE THREAD

**Issue by kapparapukeerthana** [Redth/ZXing.Net.Maui#181]
I am using the CameraBarcodeReaderView(Zxing) in my xaml for barcodesDetected. We also use laser scan for scanning. Laser scan is working until the zxing is triggered. Once zxing is used, laser scan stopped working.     
I used unloaded event to disconnect the handler, but it is not working even then.

barcodeReader?.Handler?.DisconnectHandler();    

Please provide any workaround for this. Thanks in advance

**Comment by cakmak-serkan** [comment]
I am having same issue to resolve.

workaround 
For mobile users render generate CameraBarcodeReaderView 
for laser scanner (MUNBYN) just display Entry than focus()

Exception is:
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Camera.Core.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Camera.Lifecycle.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.Google.Guava.ListenableFuture.dll
[CameraManagerGlobal] Connecting to camera service
[CameraRepository] Added camera: 0
[Camera2CameraInfo] Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_3
[CameraValidator] Verifying camera lens facing on C66, lensFacingInteger: null
[CameraValidator] Camera LensFacing verification failed, existing cameras: [Camera@4a30e7e[id=0]]
[CameraX] Retry init. Start time 695539612 current time 695539675
[CameraX] androidx.camera.core.impl.CameraValidator$CameraIdListIncorrectException: Expected camera missing from device.
[CameraX] 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:97)
[CameraX] 	at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2$androidx-camera-core-CameraX(CameraX.java:342)
[CameraX] 	at androidx.camera.core.CameraX$$ExternalSyntheticLambda3.run(Unknown Source:10)
[CameraX] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[CameraX] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[CameraX] 	at java.lang.Thread.run(Thread.java:923)
[CameraX] Caused by: java.lang.IllegalArgumentException: No available camera can be found
[CameraX] 	at androidx.camera.core.CameraSelector.select(CameraSelector.java:82)
[CameraX] 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:91)

**Comment by kapparapukeerthana** [comment]
I have found a workaround for this.


private async Task<ICameraInternal?> GetCameraPreview(CameraBarcodeReaderView cameraBarcodeReaderView)
{
    var status = await Permissions.CheckStatusAsync<Permissions.Camera>();
    if (status == PermissionStatus.Denied)
        return null;

    var bindingFlags = System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance;
    var strongHandlerProperty = typeof(CameraBarcodeReaderView).GetProperty("StrongHandler", bindingFlags);
    var cameraBarcodeReaderViewHandler = strongHandlerProperty.GetValue(cameraBarcodeReaderView) as CameraBarcodeReaderViewHandler;
    var manageField = typeof(CameraBarcodeReaderViewHandler).GetField("cameraManager", bindingFlags);
    var cameraManager = manageField.GetValue(cameraBarcodeReaderViewHandler);
    var cameraPreviewField = typeof(CameraBarcodeReaderViewHandler).Assembly.GetType("ZXing.Net.Maui.CameraManager").GetField("cameraPreview", bindingFlags);
    var preview = cameraPreviewField.GetValue(cameraManager) as Preview;

    return preview.Camera;
}

You can the above method in ondisappearing like 
"GetCameraPreview(barcodeReader).Result.Close(); "
I used close here because release would never reinitialize the camera again.

**Comment by gwalus** [comment]
@kapparapukeerthana 

Hi, did you manage to find a solution to this scenario?

**Comment by kapparapukeerthana** [comment]
> @kapparapukeerthana
> 
> Hi, did you manage to find a solution to this scenario?

Not yet, I almost tried may other scenario like initialisation of laser again on invoking the app, but that also did not work. If you have any workaround just let me know. 
Thanks
