### ISSUE TITLE
maximumViewportInset cannot be larger than frame iOS error

### ISSUE THREAD

**Issue by julianadormon** [Redth/ZXing.Net.Maui#63]
Hoping you can help.
I am getting the following error on start up in an iOS simulator.
The app works fine in Android. 
If I remove the Barcode xaml, the app starts up properly.
I have added my permission to my plist.
I upgraded to .net7 from 6 to no avail.
I upgraded the ZXIng reader to 0.1.0-preview.7 but could not get anything higher to work because I am targeting IOS 15.5.

![image](https://user-images.githubusercontent.com/89358714/198174132-55669835-e83d-4876-9c6b-6804bfffb52e.png)

This is the device output:

```
2022-10-26 21:05:25.904431-0500 SMobile[14236:148430] [unspecified] container_system_group_path_for_identifier: error = ((container_error_t)98) NOT_CODESIGNED
Error getting system group container for systemgroup.com.apple.configurationprofiles: 98
Failed to get profile system group container path. Overriding with expected path: /Users/macminim1/Library/Developer/CoreSimulator/Devices/0B8BF9E6-58A1-430F-A8EB-0E8B421193A9/data/Containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=14236
SecTaskCopyDebugDescription: SMobile[14236]/0#-1 LF=0
SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=14236
SecTaskCopyDebugDescription: SMobile[14236]/0#-1 LF=0
SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=14236
SecTaskCopyDebugDescription: SMobile[14236]/0#-1 LF=0
[ViewportSizing] maximumViewportInset cannot be larger than frame
ViewportSizing] minimumViewportInset cannot be larger than frame
```

This is the exception:
```
System.ArgumentNullException: Value cannot be null. (Parameter 'device')
  at at ObjCRuntime.ThrowHelper.ThrowArgumentNullException(String argumentName)
  at at ObjCRuntime.NativeObjectExtensions.GetNonNullHandle(INativeObject self, String argumentName)
  at at AVFoundation.AVCaptureDeviceInput..ctor(AVCaptureDevice device, NSError& error)
  at at ZXing.Net.Maui.CameraManager.UpdateCamera()
  at at ZXing.Net.Maui.CameraManager.UpdateCameraLocation(CameraLocation cameraLocation)
  at at ZXing.Net.Maui.CameraBarcodeReaderViewHandler.<>c.<.cctor>b__24_1(CameraBarcodeReaderViewHandler handler, ICameraBarcodeReaderView virtualView)
  at at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[ZXing.Net.Maui.ICameraBarcodeReaderView, ZXing.Net.MAUI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[ZXing.Net.Maui.CameraBarcodeReaderViewHandler, ZXing.Net.MAUI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
  at at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
  at at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
  at at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
  at at Microsoft.Maui.Handlers.ViewHandler`2[[ZXing.Net.Maui.ICameraBarcodeReaderView, ZXing.Net.MAUI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[UIKit.UIView, Microsoft.iOS, Version=15.4.700.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].SetVirtualView(IView view)
  at at Microsoft.Maui.Handlers.ViewHandler`2[[ZXing.Net.Maui.ICameraBarcodeReaderView, ZXing.Net.MAUI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[UIKit.UIView, Microsoft.iOS, Version=15.4.700.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].SetVirtualView(IElement view)
  at at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
  at at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
  at at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
  at at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
  at at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
  at at Microsoft.Maui.Handlers.LayoutHandler.SetVirtualView(IView view)
  at at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.LayoutView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
  at at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
  at at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
  at at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
  at at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
  at at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
  at at Microsoft.Maui.Handlers.LayoutHandler.SetVirtualView(IView view)
  at at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.LayoutView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
  at at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
  at at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
  at at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
  at at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
  at at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
  at at Microsoft.Maui.Handlers.ContentViewHandler.UpdateContent(IContentViewHandler handler)
  at at Microsoft.Maui.Handlers.ContentViewHandler.MapContent(IContentViewHandler handler, IContentView page)
  at at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IContentViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
  at at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
  at at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
  at at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
  at at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view)
  at at Microsoft.Maui.Handlers.ContentViewHandler.SetVirtualView(IView view)
  at at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
  at at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
  at at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
  at at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
  at at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
  at at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
  at at Microsoft.Maui.Platform.ElementExtensions.ToUIViewController(IElement view, IMauiContext context)
  at at Microsoft.Maui.Handlers.WindowHandler.MapContent(IWindowHandler handler, IWindow window)
  at at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IWindow, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IWindowHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
  at at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
  at at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
  at at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
  at at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
  at at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
  at at Microsoft.Maui.Platform.ElementExtensions.SetHandler(INativeObject nativeElement, IElement element, IMauiContext context)
  at at Microsoft.Maui.Platform.ElementExtensions.SetWindowHandler(UIWindow platformWindow, IWindow window, IMauiContext context)
  at at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(IApplication application, UIWindowScene windowScene, NSDictionary[] states)
  at at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(IUIApplicationDelegate platformApplication, IApplication application, UIApplication uiApplication, NSDictionary launchOptions)
  at at Microsoft.Maui.MauiUIApplicationDelegate.FinishedLaunching(UIApplication application, NSDictionary launchOptions)
  at at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
  at SMobile.Program.Main(String[] args) in /Users/macminim1/Projects/Sorted/SMobile/SMobile/Platforms/iOS/Program.cs:13
```

My XAML:
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:b="clr-namespace:Microsoft.AspNetCore.Components.WebView.Maui;assembly=Microsoft.AspNetCore.Components.WebView.Maui"
             xmlns:local="clr-namespace:SMobile"
             xmlns:data="clr-namespace:SMobile.Data"
             xmlns:zxing="clr-namespace:ZXing.Net.Maui.Controls;assembly=ZXing.Net.MAUI"
             x:Class="SMobile.MainPage"
             BackgroundColor="{DynamicResource PageBackgroundColor}">

    <ContentPage.Resources>
        <data:ShowQrReaderConverter x:Key="ShowQrReaderConverter"/>
        <data:ShowFrCapturingConverter x:Key="ShowFrCapturingConverter"/>
    </ContentPage.Resources>

    <AbsoluteLayout>
        <b:BlazorWebView HostPage="wwwroot/index.html" 
                         AbsoluteLayout.LayoutBounds="0, 0, 1, 1" 
                         AbsoluteLayout.LayoutFlags="All">
            <b:BlazorWebView.RootComponents>
                <b:RootComponent Selector="#app" ComponentType="{x:Type local:Main}" />
            </b:BlazorWebView.RootComponents>
        </b:BlazorWebView>

        <!-- QR Reader -->
        <AbsoluteLayout
            x:Name="absLayout"
            Margin="0,334"
            BackgroundColor="Beige"
            HeightRequest="{Binding availableQrReaderHeight}"
            WidthRequest="{Binding availableQrReaderWidth}"
            >
            <AbsoluteLayout.TranslationX>
                <MultiBinding Converter="{StaticResource ShowQrReaderConverter}">
                    <Binding Path="CardToggle" />
                    <Binding Path="qrReaderDetecting" />
                    <Binding Path="AppState.ShootMode" />
                </MultiBinding>
            </AbsoluteLayout.TranslationX>

            <zxing:CameraBarcodeReaderView
                x:Name="barcodeReader"
                IsDetecting="{Binding qrReaderDetecting}"
                IsVisible="{Binding qrReaderVisible}"
                IsTorchOn="False" 
                BarcodesDetected="CameraBarcodeReaderView_BarcodesDetected"
                >
            </zxing:CameraBarcodeReaderView>
            
        </AbsoluteLayout>

    </AbsoluteLayout>
</ContentPage>
```

My Plist
![image](https://user-images.githubusercontent.com/89358714/198175360-f8217def-0fc1-43d8-b057-d0e0a51bade0.png)

**Comment by JulienMontfort** [comment]
Hello, 

I have the same bug with following configuration : 

- Net.6
- ZXING.Net.Maui 0.2.0-preview.2
- Tested on IOS 13.2 on real device.
- Tested on IOS 15.6 on real device, 
- Tested on IOS 16 on simulator.

**Comment by julianadormon** [comment]
@JulienMontfort 2 Julians with the same issue, what are the odds!

A couple of questions for you:

1. What version of XCode are you on? When I ran the latest, none of the IOS simulators would appear for me in Visual Studio.
I had to roll back to 13.4.1 and that does not show any simulators > iOS 15.5.

2. Are you running Maui or Maui Blazor? Not sure if the team is testing in Blazor, running the scanner control alongside the webview control. It should not be a problem, but I cannot be sure.

Perhaps if you post your error and set up details, that will help them determine the cause faster. Thanks.

**Comment by JulienMontfort** [comment]
@julianadormon you can rename the post to Julians Bug ^^

1 I'm using XCode 14.0.1. The Mac linked to my PC with Visual Studio 17.3.6. IOS simulatos appear in Visual Studio. But when y add a local device or new Simulator, i need to reconnect for updating the list.

2 I did some tests on Maui and Maui Blazor. I have the same issue. I have previously used ZXingBlazor NuGet package but not working on IOS. 

When you using camera, the simulator replace camera with a video.

##  Visual studio screen shot : 

![2022-10-27_13h55_33](https://user-images.githubusercontent.com/95291011/198277824-a1de4cc0-d0bc-41ac-b8af-5f97a4ca4111.png)


##  Visual studio output : 
>2022-10-27 13:54:48.691473+0200 SwImpulseClient[79860:1072752] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=79860
2022-10-27 13:54:48.692147+0200 SwImpulseClient[79860:1072752] SecTaskCopyDebugDescription: SwImpulseClient[79860]/0#-1 LF=0
**System.ArgumentNullException:** 'Value cannot be null. (Parameter 'device')'
Thread finished: <Thread Pool> #9
Thread finished: <Thread Pool> #10
The thread 0x9 has exited with code 0 (0x0).
The thread 0xa has exited with code 0 (0x0).
Thread finished: <Thread Pool> #7
Thread started: <Thread Pool> #12
The thread 0x7 has exited with code 0 (0x0).
The thread 0xb has exited with code 0 (0x0).
Thread finished: <Thread Pool> #11
Thread started: <Thread Pool> #13
Thread started: <Thread Pool> #14
The thread 0xc has exited with code 0 (0x0).
The thread 0xe has exited with code 0 (0x0).
Thread finished: <Thread Pool> #12
Thread finished: <Thread Pool> #14
Thread started: <Thread Pool> #15
2022-10-27 13:59:10.800182+0200 SwImpulseClient[79860:1072752] 
Unhandled Exception:
System.ArgumentNullException: Value cannot be null. (Parameter 'device')
   at ObjCRuntime.ThrowHelper.ThrowArgumentNullException(String argumentName)
   at ObjCRuntime.NativeObjectExtensions.GetNonNullHandle(INativeObject self, String argumentName)
   at AVFoundation.AVCaptureDeviceInput..ctor(AVCaptureDevice device, NSError& error)
   at ZXing.Net.Maui.CameraManager.UpdateCamera()
   at ZXing.Net.Maui.CameraManager.Connect()
   at ZXing.Net.Maui.CameraBarcodeReaderViewHandler.ConnectHandler(UIView nativeView)
   at ObjCRuntime.Runtime.ThrowException(IntPtr gchandle)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at SwImpulseClient.Program.Main(String[] args) in C:\Users\julien.montfort\Desktop\SW_IMPULSE_MOBILE_BLAZOR\SwImpulseClient\Platforms\iOS\Program.cs:l
ine 13
2022-10-27 13:59:10.800980+0200 SwImpulseClient[79860:1072752] Unhandled managed exception: Value cannot be null. (Parameter 'device') (System.ArgumentNullException)
   at ObjCRuntime.ThrowHelper.ThrowArgumentNullException(String argumentName)
   at ObjCRuntime.NativeObjectExtensions.GetNonNullHandle(INativeObject self, String argumentName)
   at AVFoundation.AVCaptureDeviceInput..ctor(AVCaptureDevice device, NSError& error)
   at ZXing.Net.Maui.CameraManager.UpdateCamera()
   at ZXing.Net.Maui.CameraManager.Connect()
   at ZXing.Net.Maui.CameraBarcodeReaderViewHandler.ConnectHandler(UIView nativeView)
   at ObjCRuntime.Runtime.ThrowException(IntPtr gchandle)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at SwImpulseClient.Program.Main(String[] args) in C:\Users\julien.montfort\Desktop\SW_IMPULSE_MOBILE_BLAZOR\SwImpulseClient\Platforms\i
OS\Program.cs:line 13
=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
=================================================================
	Native stacktrace:
=================================================================
	0x10cdbdb84 - /Users/julien.montfort/Library/Developer/CoreSimulator/Devices/77A6C342-A806-451C-9112-58A7C9C3BC4A/data/Containers/Bundle/Application/3A151A8A-2F45-4694-9EC3-0A3EE93A30F8/SwImpulseClient.app/libmonosgen-2.0.dylib : mono_dump_native_crash_info
	0x10cd601fe - /Users/julien.montfort/Library/Developer/CoreSimulator/Devices/77A6C342-A806-451C-9112-58A7C9C3BC4A/data/Containers/Bundle/Application/3A151A8A-2F45-4694-9EC3-0A3EE93A30F8/SwImpulseClient.app/libmonosgen-2.0.dylib : mono_handle_native_crash
	0x10cdbd492 - /Users/julien.montfort/Library/Developer/CoreSimulator/Devices/77A6C342-A806-451C-9112-58A7C9C3BC4A/data/Containers/Bundle/Application/3A151A8A-2F45-4694-9EC3-0A3EE93A30F8/SwImpulseClient.app/libmonosgen-2.0.dylib : sigabrt_signal_handler
	0x7ff833e30dfd - /usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x0 - Unknown
	0x11fe65fe0 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libsystem_c.dylib : abort
	0x10c5f0597 - /Users/julien.montfort/Library/Developer/CoreSimulator/Devices/77A6C342-A806-451C-9112-58A7C9C3BC4A/data/Containers/Bundle/Application/3A151A8A-2F45-4694-9EC3-0A3EE93A30F8/SwImpulseClient.app/libxamarin-dotnet-debug.dylib : xamarin_unhandled_exception_handler
	0x10cb99a55 - /Users/julien.montfort/Library/Developer/CoreSimulator/Devices/77A6C342-A806-451C-9112-58A7C9C3BC4A/data/Containers/Bundle/Application/3A151A8A-2F45-4694-9EC3-0A3EE93A30F8/SwImpulseClient.app/libmonosgen-2.0.dylib : mono_invoke_unhandled_exception_hook
	0x10cd5fe24 - /Users/julien.montfort/Library/Developer/CoreSimulator/Devices/77A6C342-A806-451C-9112-58A7C9C3BC4A/data/Containers/Bundle/Application/3A151A8A-2F45-4694-9EC3-0A3EE93A30F8/SwImpulseClient.app/libmonosgen-2.0.dylib : mono_handle_exception_internal
	0x10cd5e103 - /Users/julien.montfort/Library/Developer/CoreSimulator/Devices/77A6C342-A806-451C-9112-58A7C9C3BC4A/data/Containers/Bundle/Application/3A151A8A-2F45-4694-9EC3-0A3EE93A30F8/SwImpulseClient.app/libmonosgen-2.0.dylib : mono_handle_exception
	0x10cdce87d - /Users/julien.montfort/Library/Developer/CoreSimulator/Devices/77A6C342-A806-451C-9112-58A7C9C3BC4A/data/Containers/Bundle/Application/3A151A8A-2F45-4694-9EC3-0A3EE93A30F8/SwImpulseClient.app/libmonosgen-2.0.dylib : interp_throw
	0x10cdc0bbc - /Users/julien.montfort/Library/Developer/CoreSimulator/Devices/77A6C342-A806-451C-9112-58A7C9C3BC4A/data/Containers/Bundle/Application/3A151A8A-2F45-4694-9EC3-0A3EE93A30F8/SwImpulseClient.app/libmonosgen-2.0.dylib : interp_exec_method
	0x10cdbf10f - /Users/julien.montfort/Library/Developer/CoreSimulator/Devices/77A6C342-A806-451C-9112-58A7C9C3BC4A/data/Containers/Bundle/Application/3A151A8A-2F45-4694-9EC3-0A3EE93A30F8/SwImpulseClient.app/libmonosgen-2.0.dylib : interp_runtime_invoke
	0x10cbe1a78 - /Users/julien.montfort/Library/Developer/CoreSimulator/Devices/77A6C342-A806-451C-9112-58A7C9C3BC4A/data/Containers/Bundle/Application/3A151A8A-2F45-4694-9EC3-0A3EE93A30F8/SwImpulseClient.app/libmonosgen-2.0.dylib : mono_runtime_invoke_checked
	0x10cbe99cc - /Users/julien.montfort/Library/Developer/CoreSimulator/Devices/77A6C342-A806-451C-9112-58A7C9C3BC4A/data/Containers/Bundle/Application/3A151A8A-2F45-4694-9EC3-0A3EE93A30F8/SwImpulseClient.app/libmonosgen-2.0.dylib : do_exec_main_checked
	0x10cd1b062 - /Users/julien.montfort/Library/Developer/CoreSimulator/Devices/77A6C342-A806-451C-9112-58A7C9C3BC4A/data/Containers/Bundle/Application/3A151A8A-2F45-4694-9EC3-0A3EE93A30F8/SwImpulseClient.app/libmonosgen-2.0.dylib : mono_jit_exec
	0x10c603e77 - /Users/julien.montfort/Library/Developer/CoreSimulator/Devices/77A6C342-A806-451C-9112-58A7C9C3BC4A/data/Containers/Bundle/Application/3A151A8A-2F45-4694-9EC3-0A3EE93A30F8/SwImpulseClient.app/libxamarin-dotnet-debug.dylib : xamarin_main
	0x10bb423e4 - /Users/julien.montfort/Library/Developer/CoreSimulator/Devices/77A6C342-A806-451C-9112-58A7C9C3BC4A/data/Containers/Bundle/Application/3A151A8A-2F45-4694-9EC3-0A3EE93A30F8/SwImpulseClient.app/SwImpulseClient : main
	0x10c29d2bf - Unknown
	0x11772852e - Unknown
=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x7ff833de600e):0x7ff833de5ffe  ff ff c3 90 90 90 b8 48 01 00 02 49 89 
ca 0f 05 
 .......H...I....
0x7ff833de600e  73 08 48 89 c7 e9 ad a1 ff ff c3 90 90 
90 b8 53  s.H..
..........S
0x7ff833de601e  00 00 02 49 89 
ca 0f 05 73 08 48 89 c7 e9 95 a1  .
..I....s.H
.....
0x7ff833de602e  ff ff c3 90 
90 90 b8 83 01 00 02 49 89 ca 
0f 05  ........
...I....
=================================================================
	Managed Stacktrace:
=================================================================
=================================================================
The app has been terminated.

**Comment by julianadormon** [comment]
To follow up on this, I was able to run this on an actual iPhone 11 running iOS16 without getting the error.
I am however getting an issue where the camera view is not appearing but the scan is working nonetheless. I see that others have posted about this recently.  So as far as Julian #1 is concerned, I am ok on this issue. Julien #2, I hope they can shed some light.

**Comment by jfversluis** [comment]
Thanks for the detailed report. This is from the early iOS/.NET 6/.NET 7 preview timeframe, and the iOS/MacCatalyst camera setup and preview orientation code has changed since then.

Please try the latest version. If you still see `maximumViewportInset cannot be larger than frame`, open a new issue with the current package version, .NET version, iOS version, device/simulator target, and a minimal repro project or page.
