### ISSUE TITLE
[AVCaptureDevice setTorchMode:] May not be called without first successfully gaining exclusive ownership of the device using -lockForConfiguration:'

### ISSUE THREAD

**Issue by DuckScapePhilip** [Redth/ZXing.Net.Maui#92]
The app crashes on iOS 16.1 when I open the barcode scanner. It throws the exception below:

```
*** Terminating app due to uncaught exception 'NSGenericException', reason: '*** -[AVCaptureDevice setTorchMode:] May not be called without first successfully gaining exclusive ownership of the device using -lockForConfiguration:'
```

**Comment by Godfather95** [comment]
Got the same problem with iOS 16.1.2 on iPhone SE using `net7.0-ios` and `ZXing.Net.Maui (1.0.0)`. If i can help with additional information, i will be happy to provide it.

`[0:] An error occurred: 'Objective-C exception thrown.  Name: NSGenericException Reason: *** -[AVCaptureDevice setTorchMode:] May not be called without first successfully gaining exclusive ownership of the device using -lockForConfiguration:
Native stack trace:
	0   CoreFoundation                      0x00000001a3821e94 5CDC5D9A-E506-3740-B64E-BB30867B4F1B + 40596
	1   libobjc.A.dylib                     0x000000019cb578d8 objc_exception_throw + 60
	2   AVFCapture                          0x00000001bc87b11c 78D39DD1-0D94-333B-AF89-78B13D83F84D + 184604
	3   Xamarin.PreBuilt.iOS                0x0000000100c3b960 _ZN16XamarinCallState3selEv + 3468
	4   Xamarin.PreBuilt.iOS                0x0000000100f299dc _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2343984
	5   Xamarin.PreBuilt.iOS                0x0000000100f28770 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2339268
	6   Xamarin.PreBuilt.iOS                0x0000000100f1e14c _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2296736
	7   Xamarin.PreBuilt.iOS                0x0000000100f1bd8c _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2287584
	8   Xamarin.PreBuilt.iOS                0x0000000100eecd94 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2095080
	9   Xamarin.PreBuilt.iOS                0x0000000100e3bd70 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 1370052
	10  Xamarin.PreBuilt.iOS                0x0000000100e3f410 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 1384036
	11  Xamarin.PreBuilt.iOS                0x0000000100c34964 _Z9__isctypeim + 32304
	12  Xamarin.PreBuilt.iOS                0x0000000100c3ab90 xamarin_get_original_working_directory_path + 4484
	13  Xamarin.PreBuilt.iOS                0x0000000100c3b834 _ZN16XamarinCallState3selEv + 3168
	14  UIKitCore                           0x00000001a5c23d34 179501B6-0FC2-344A-B969-B4E3961EBE10 + 2420020
	15  UIKitCore                           0x00000001a5c23a34 179501B6-0FC2-344A-B969-B4E3961EBE10 + 2419252
	16  UIKitCore                           0x00000001a5c233c8 179501B6-0FC2-344A-B969-B4E3961EBE10 + 2417608
	17  UIKitCore                           0x00000001a5c2326c 179501B6-0FC2-344A-B969-B4E3961EBE10 + 2417260
	18  UIKitCore                           0x00000001a5c22ea4 179501B6-0FC2-344A-B969-B4E3961EBE10 + 2416292
	19  UIKitCore                           0x00000001a5ad1868 179501B6-0FC2-344A-B969-B4E3961EBE10 + 1034344
	20  UIKitCore                           0x00000001a5ad0c84 179501B6-0FC2-344A-B969-B4E3961EBE10 + 1031300
	21  UIKitCore                           0x00000001a5acff44 179501B6-0FC2-344A-B969-B4E3961EBE10 + 1027908
	22  UIKitCore                           0x00000001a5acf600 179501B6-0FC2-344A-B969-B4E3961EBE10 + 1025536
	23  UIKitCore                           0x00000001a5b173e4 179501B6-0FC2-344A-B969-B4E3961EBE10 + 1319908
	24  UIKitCore                           0x00000001a5e20160 179501B6-0FC2-344A-B969-B4E3961EBE10 + 4501856
	25  CoreFoundation                      0x00000001a38edf54 5CDC5D9A-E506-3740-B64E-BB30867B4F1B + 876372
	26  CoreFoundation                      0x00000001a38fa32c 5CDC5D9A-E506-3740-B64E-BB30867B4F1B + 926508
	27  CoreFoundation                      0x00000001a387e210 5CDC5D9A-E506-3740-B64E-BB30867B4F1B + 418320
	28  CoreFoundation                      0x00000001a3893ba8 5CDC5D9A-E506-3740-B64E-BB30867B4F1B + 506792
	29  CoreFoundation                      0x00000001a3898ed4 CFRunLoopRunSpecific + 612
	30  GraphicsServices                    0x00000001dcb9a368 GSEventRunModal + 164
	31  UIKitCore                           0x00000001a5d773d0 179501B6-0FC2-344A-B969-B4E3961EBE10 + 3810256
	32  UIKitCore                           0x00000001a5d77034 UIApplicationMain + 340
	33  Xamarin.PreBuilt.iOS                0x0000000100c105a4 xamarin_UIApplicationMain + 60
	34  Xamarin.PreBuilt.iOS                0x0000000100f29a50 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2344100
	35  Xamarin.PreBuilt.iOS                0x0000000100f28770 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2339268
	36  Xamarin.PreBuilt.iOS                0x0000000100f1e14c _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2296736
	37  Xamarin.PreBuilt.iOS                0x0000000100f1bd8c _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2287584
	38  Xamarin.PreBuilt.iOS                0x0000000100eecd94 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2095080
	39  Xamarin.PreBuilt.iOS                0x0000000100e3bd70 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 1370052
	40  Xamarin.PreBuilt.iOS                0x0000000100e42cc0 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 1398548
	41  Xamarin.PreBuilt.iOS                0x0000000100e03a30 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 1139844
	42  Xamarin.PreBuilt.iOS                0x0000000100e0ce74 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 1177800
	43  Xamarin.PreBuilt.iOS                0x0000000100f29a1c _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2344048
	44  Xamarin.PreBuilt.iOS                0x0000000100f287a8 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2339324
	45  Xamarin.PreBuilt.iOS                0x0000000100f1e14c _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2296736
	46  Xamarin.PreBuilt.iOS                0x0000000100f1bd8c _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2287584
	47  Xamarin.PreBuilt.iOS                0x0000000100eecd94 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2095080
	48  Xamarin.PreBuilt.iOS                0x0000000100e3bd70 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 1370052
	49  Xamarin.PreBuilt.iOS                0x0000000100e42618 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 1396844
	50  Xamarin.PreBuilt.iOS                0x0000000100ef1f90 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2116068
	51  Xamarin.PreBuilt.iOS                0x0000000100c3a9bc xamarin_get_original_working_directory_path + 4016
	52  Xamarin.PreBuilt.iOS                0x0000000100f580b4 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2534152
	53  dyld                                0x00000001c1f04960 CB3FF411-4762-34D2-86A4-ECA13F9FB6C3 + 88416
'. Callstack: '   at AVFoundation.AVCaptureDevice.set_TorchMode(AVCaptureTorchMode value)
   at ZXing.Net.Maui.CameraManager.UpdateTorch(Boolean on)
   at ZXing.Net.Maui.CameraBarcodeReaderViewHandler.<>c.<.cctor>b__23_0(CameraBarcodeReaderViewHandler handler, ICameraBarcodeReaderView virtualView)
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[ZXing.Net.Maui.ICameraBarcodeReaderView, ZXing.Net.MAUI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[ZXing.Net.Maui.CameraBarcodeReaderViewHandler, ZXing.Net.MAUI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[ZXing.Net.Maui.ICameraBarcodeReaderView, ZXing.Net.MAUI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[UIKit.UIView, Microsoft.iOS, Version=16.1.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[ZXing.Net.Maui.ICameraBarcodeReaderView, ZXing.Net.MAUI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[UIKit.UIView, Microsoft.iOS, Version=16.1.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
   at Microsoft.Maui.Handlers.LayoutHandler.SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.LayoutView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
   at Microsoft.Maui.Handlers.ContentViewHandler.UpdateContent(IContentViewHandler handler)
   at Microsoft.Maui.Handlers.ContentViewHandler.MapContent(IContentViewHandler handler, IContentView page)
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IContentViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ContentViewHandler.SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ViewExtensions.ToHandler(IView view, IMauiContext context)
   at CommunityToolkit.Maui.Views.Popup.<MapOnOpened>g__CreatePageHandler|0_0(IPopup virtualView) in /_/src/CommunityToolkit.Maui/HandlerImplementation/Popup/Popup.macios.cs:line 33
   at CommunityToolkit.Maui.Core.Views.MauiPopup.CreateControl(Func`2 func, IPopup& virtualView) in /_/src/CommunityToolkit.Maui.Core/Views/Popup/MauiPopup.macios.cs:line 120
   at CommunityToolkit.Maui.Views.Popup.MapOnOpened(PopupHandler handler, IPopup view, Object result) in /_/src/CommunityToolkit.Maui/HandlerImplementation/Popup/Popup.macios.cs:line 18
   at Microsoft.Maui.CommandMapper`2.<>c__DisplayClass6_0[[CommunityToolkit.Maui.Core.IPopup, CommunityToolkit.Maui.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[CommunityToolkit.Maui.Core.Handlers.PopupHandler, CommunityToolkit.Maui.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v, Object o)
   at Microsoft.Maui.CommandMapper.InvokeCore(String key, IElementHandler viewHandler, IElement virtualView, Object args)
   at Microsoft.Maui.CommandMapper.Invoke(IElementHandler viewHandler, IElement virtualView, String property, Object args)
   at Microsoft.Maui.Handlers.ElementHandler.Invoke(String command, Object args)
   at CommunityToolkit.Maui.Views.PopupExtensions.CreatePopup(Page page, Popup popup) in /_/src/CommunityToolkit.Maui/Views/Popup/PopupExtensions.shared.cs:line 60
   at CommunityToolkit.Maui.Views.PopupExtensions.ShowPopupAsync[Popup](Page page, Popup popup) in /_/src/CommunityToolkit.Maui/Views/Popup/PopupExtensions.shared.cs:line 50
   at SWS.PZECloud.ViewModels.SetupViewModel.SetupAppWithBarcode(Boolean StartSetup) in E:\github\pze-terminal-app\src\pze-terminal-app\ViewModels\SetupViewModel.cs:line 103
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Foundation.NSAsyncSynchronizationContextDispatcher.Apply()
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at SWS.PZECloud.Program.Main(String[] args) in E:\github\pze-terminal-app\src\pze-terminal-app\Platforms\iOS\Program.cs:line 12
   at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)'`

**Comment by DuckScapePhilip** [comment]
I downloaded the code, and validated that it is locking before setting the torch mode.

Also, their barcode sample application works just fine. So I am confused why it is suddenly breaking for me.

**Comment by jfversluis** [comment]
Thanks for the report. The current Apple torch implementation takes the AVCaptureDevice configuration lock before setting torch mode, and related Apple camera teardown fixes have landed since this was reported.

Please try the latest version. If this still crashes, open a new issue with the current package version, iOS version, device model, whether torch is set before/after camera startup, and a minimal repro.
